### ISSUE TITLE
[Suggestion] Addition of GT metal tool parts to the smeltery via config instead of GT alloy smelter/extruder

### ISSUE THREAD

**Issue by Invincible92** [Vexatos/TinkersGregworks#15]
As the title says, could be possible to add all metal tool parts directly to be casted in the TiCon Smeltery instead of being crafted via GT alloy smelter/extruder? In case of if being possible, could them being added with the melting point that GT states for the molten metals?

I'm currently replacing via MineTweaker all TiCo metals that have an equivalent in GT with the TiGregworks counterpart, and using the correct temperatures, but it's a tedious procedure the replacement and search of the meta-materials.

**Comment by Vexatos** [comment]
TGregworks is primarily a GregTech addon, that's why it uses GregTech machines. In fact, since version 1.0.8 it is fully usable without the TConstruct smeltery (i.e. you could disable the smeltery without losing access to any kind of tool). I will not add a config option for smeltery recipes simply because then it would be more of a TCon addon than a GregTech addon, and I want people to use GregTech machines.
