### ISSUE TITLE
[Suggestion] Adding Ingot support for Tool repair

### ISSUE THREAD

**Issue by Dream-Master** [Vexatos/TinkersGregworks#20]
Adding Ingot support for Tool repair please.

**Comment by Dream-Master** [comment]
:+1:

**Comment by Vexatos** [comment]
Should be in version 1.0.9 of TGregworks. Go give it a try.

**Comment by Dream-Master** [comment]
Thanks will look into it.

@Vexatos 
Btw did i can use your Mod in a public Modpack? We want to go public soon. At the moment we are a private modpack.

https://github.com/GTNewHorizons/NewHorizons

**Comment by Vexatos** [comment]
Hmm... Is the smeltery entirely gone in this mod pack? You might want to disable some TCon materials entirely since they overpower pretty much every GregTech material (Alumite and higher, pretty much). Of course, you do not have to.

So yes, you have permission to use it in that mod pack. It looks interesting.
